Updated classifiers in setup.cfg
ansible/ansible-sdk pull request #48
Opened 2022-11-03 14:49 UTC by Akasurde

##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
setup.cfg

2022-11-03 15:13 UTC, eqrx approved these changes

2022-11-03 15:24 UTC, Shrews requested changes

2022-11-03 15:24 UTC, Shrews commented on setup.cfg
> +classifiers = [
I don't believe the format of this is correct for a `setup.cfg` (but is within `setup.py`).

2022-11-04 10:38 UTC, Akasurde commented
superseded by #49

2022-11-04 10:38 UTC, closed without merging